# action.yml
name: 'Deploy MkDocs'
description: 'Deploys MkDocs site'
author: 'didier Bröska, didier.broska@gmail.com'
branding:
  icon: 'arrow-up-circle'  
  color: 'orange'
runs: |
  python -m pip install --upgrade pip mkdocs
  mkdocs gh-deploy --config-file $"{GITHUB_WORKSPACE}/mkdocs.yml" --force

